services:
    hookhub-db:
        image: postgres:17
        container_name: hookhub-pg
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hookhub
        ports:
            - "5432:5432"
